version: '2'

services:
  app:
    image: 'spring-boot-demo:v3'
    ports:
      - "8080:8080"
    build:
      context: ../../..
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/student
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=student
#    expose:
#      - "5332"
#    ports:
#      - "5332:5432"
#    command: -p 5332